require_relative('../models/genre')

####GENRE SEEDS
genre1 = Genre.new({"name" => "Crime"})
genre1.save()
genre2 = Genre.new({"name" => "Fantasy"})
genre2.save()
genre3 = Genre.new({"name" => "Sci-Fi"})
genre3.save()
genre4 = Genre.new({"name" => "Thriller"})
genre4.save()
genre5 = Genre.new({"name" => "Horror"})
genre5.save()
genre6 = Genre.new({"name" => "Young Adult"})
genre6.save()
genre7 = Genre.new({"name" => "Non-Fiction"})
genre7.save()
genre8 = Genre.new({"name" => "Classic"})
genre8.save()
genre9 = Genre.new({"name" => "Literary Fiction"})
genre9.save()
